package sizebay.catalog.client.model;

public enum ClothesType {
	FULL_BODY,
	BOTTOM,
	TOP,
	UNDERWEAR_FULL_BODY,
	UNDERWEAR_BOTTOM,
	UNDERWEAR_TOP,
	WETSUIT_FULL_BODY,
	WETSUIT_BOTTOM,
	WETSUIT_TOP
}